language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c "CREATE DATABASE rmwtests;" -U postgres
  - psql -c "CREATE USER adminride WITH PASSWORD 'ridemyway1';" -U postgres

script: 
  - py.test --cov=tests

after_success:
- coveralls
